# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './testGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

try:
    _fromUtf8 = QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1163, 791)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget_2 = QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QRect(10, 20, 1081, 691))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.splitter = QSplitter(self.tab_5)
        self.splitter.setGeometry(QRect(10, 20, 820, 394))
        self.splitter.setOrientation(Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget = QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_8 = QVBoxLayout(self.widget)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_30 = QLabel(self.widget)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_8.addWidget(self.label_30)
        self.horizontalLayout_19 = QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_31 = QLabel(self.widget)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout.addWidget(self.label_31)
        self.horizontalLayout_12 = QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_A_1__B_1 = QLineEdit(self.widget)
        self.label_A_1__B_1.setObjectName(_fromUtf8("label_A_1__B_1"))
        self.horizontalLayout_12.addWidget(self.label_A_1__B_1)
        self.label_A_1__B_2 = QLineEdit(self.widget)
        self.label_A_1__B_2.setObjectName(_fromUtf8("label_A_1__B_2"))
        self.horizontalLayout_12.addWidget(self.label_A_1__B_2)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.label = QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.keyBind__A_1__B_1 = QLineEdit(self.widget)
        self.keyBind__A_1__B_1.setObjectName(_fromUtf8("keyBind__A_1__B_1"))
        self.horizontalLayout_2.addWidget(self.keyBind__A_1__B_1)
        self.keyBind__A_1__B_2 = QLineEdit(self.widget)
        self.keyBind__A_1__B_2.setObjectName(_fromUtf8("keyBind__A_1__B_2"))
        self.horizontalLayout_2.addWidget(self.keyBind__A_1__B_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.padBind__A_1__B_1 = QLineEdit(self.widget)
        self.padBind__A_1__B_1.setObjectName(_fromUtf8("padBind__A_1__B_1"))
        self.horizontalLayout.addWidget(self.padBind__A_1__B_1)
        self.padBind__A_1__B_2 = QLineEdit(self.widget)
        self.padBind__A_1__B_2.setObjectName(_fromUtf8("padBind__A_1__B_2"))
        self.horizontalLayout.addWidget(self.padBind__A_1__B_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_19.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_32 = QLabel(self.widget)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_2.addWidget(self.label_32)
        self.horizontalLayout_17 = QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_A_1__B_3 = QLineEdit(self.widget)
        self.label_A_1__B_3.setObjectName(_fromUtf8("label_A_1__B_3"))
        self.horizontalLayout_17.addWidget(self.label_A_1__B_3)
        self.label_A_1__B_4 = QLineEdit(self.widget)
        self.label_A_1__B_4.setObjectName(_fromUtf8("label_A_1__B_4"))
        self.horizontalLayout_17.addWidget(self.label_A_1__B_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.label_5 = QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_14 = QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.keyBind__A_1__B_3 = QLineEdit(self.widget)
        self.keyBind__A_1__B_3.setObjectName(_fromUtf8("keyBind__A_1__B_3"))
        self.horizontalLayout_14.addWidget(self.keyBind__A_1__B_3)
        self.keyBind__A_1__B_4 = QLineEdit(self.widget)
        self.keyBind__A_1__B_4.setObjectName(_fromUtf8("keyBind__A_1__B_4"))
        self.horizontalLayout_14.addWidget(self.keyBind__A_1__B_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.label_6 = QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_13 = QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.padBind__A_1__B_3 = QLineEdit(self.widget)
        self.padBind__A_1__B_3.setObjectName(_fromUtf8("padBind__A_1__B_3"))
        self.horizontalLayout_13.addWidget(self.padBind__A_1__B_3)
        self.padBind__A_1__B_4 = QLineEdit(self.widget)
        self.padBind__A_1__B_4.setObjectName(_fromUtf8("padBind__A_1__B_4"))
        self.horizontalLayout_13.addWidget(self.padBind__A_1__B_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_19.addLayout(self.verticalLayout_2)
        self.verticalLayout_7 = QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_33 = QLabel(self.widget)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalLayout_7.addWidget(self.label_33)
        self.horizontalLayout_18 = QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_A_1__B_5 = QLineEdit(self.widget)
        self.label_A_1__B_5.setObjectName(_fromUtf8("label_A_1__B_5"))
        self.horizontalLayout_18.addWidget(self.label_A_1__B_5)
        self.label_A_1__B_6 = QLineEdit(self.widget)
        self.label_A_1__B_6.setObjectName(_fromUtf8("label_A_1__B_6"))
        self.horizontalLayout_18.addWidget(self.label_A_1__B_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.label_7 = QLabel(self.widget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_7.addWidget(self.label_7)
        self.horizontalLayout_16 = QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.keyBind__A_1__B_5 = QLineEdit(self.widget)
        self.keyBind__A_1__B_5.setObjectName(_fromUtf8("keyBind__A_1__B_5"))
        self.horizontalLayout_16.addWidget(self.keyBind__A_1__B_5)
        self.keyBind__A_1__B_6 = QLineEdit(self.widget)
        self.keyBind__A_1__B_6.setObjectName(_fromUtf8("keyBind__A_1__B_6"))
        self.horizontalLayout_16.addWidget(self.keyBind__A_1__B_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.label_8 = QLabel(self.widget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_7.addWidget(self.label_8)
        self.horizontalLayout_15 = QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.padBind__A_1__B_5 = QLineEdit(self.widget)
        self.padBind__A_1__B_5.setObjectName(_fromUtf8("padBind__A_1__B_5"))
        self.horizontalLayout_15.addWidget(self.padBind__A_1__B_5)
        self.padBind__A_1__B_6 = QLineEdit(self.widget)
        self.padBind__A_1__B_6.setObjectName(_fromUtf8("padBind__A_1__B_6"))
        self.horizontalLayout_15.addWidget(self.padBind__A_1__B_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_19.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.layoutWidget_12 = QWidget(self.splitter)
        self.layoutWidget_12.setObjectName(_fromUtf8("layoutWidget_12"))
        self.verticalLayout_9 = QVBoxLayout(self.layoutWidget_12)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_38 = QLabel(self.layoutWidget_12)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.verticalLayout_9.addWidget(self.label_38)
        self.horizontalLayout_20 = QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.verticalLayout_10 = QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_76 = QLabel(self.layoutWidget_12)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.verticalLayout_10.addWidget(self.label_76)
        self.horizontalLayout_21 = QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_A_1__B_7 = QLineEdit(self.layoutWidget_12)
        self.label_A_1__B_7.setObjectName(_fromUtf8("label_A_1__B_7"))
        self.horizontalLayout_21.addWidget(self.label_A_1__B_7)
        self.label_A_1__B_8 = QLineEdit(self.layoutWidget_12)
        self.label_A_1__B_8.setObjectName(_fromUtf8("label_A_1__B_8"))
        self.horizontalLayout_21.addWidget(self.label_A_1__B_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_21)
        self.label_3 = QLabel(self.layoutWidget_12)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_10.addWidget(self.label_3)
        self.horizontalLayout_22 = QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.keyBind__A_1__B_7 = QLineEdit(self.layoutWidget_12)
        self.keyBind__A_1__B_7.setObjectName(_fromUtf8("keyBind__A_1__B_7"))
        self.horizontalLayout_22.addWidget(self.keyBind__A_1__B_7)
        self.keyBind__A_1__B_8 = QLineEdit(self.layoutWidget_12)
        self.keyBind__A_1__B_8.setObjectName(_fromUtf8("keyBind__A_1__B_8"))
        self.horizontalLayout_22.addWidget(self.keyBind__A_1__B_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_22)
        self.label_4 = QLabel(self.layoutWidget_12)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_10.addWidget(self.label_4)
        self.horizontalLayout_23 = QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.padBind__A_1__B_7 = QLineEdit(self.layoutWidget_12)
        self.padBind__A_1__B_7.setObjectName(_fromUtf8("padBind__A_1__B_7"))
        self.horizontalLayout_23.addWidget(self.padBind__A_1__B_7)
        self.padBind__A_1__B_8 = QLineEdit(self.layoutWidget_12)
        self.padBind__A_1__B_8.setObjectName(_fromUtf8("padBind__A_1__B_8"))
        self.horizontalLayout_23.addWidget(self.padBind__A_1__B_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_20.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_77 = QLabel(self.layoutWidget_12)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.verticalLayout_11.addWidget(self.label_77)
        self.horizontalLayout_24 = QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_A_1__B_9 = QLineEdit(self.layoutWidget_12)
        self.label_A_1__B_9.setObjectName(_fromUtf8("label_A_1__B_9"))
        self.horizontalLayout_24.addWidget(self.label_A_1__B_9)
        self.label_A_1__B_10 = QLineEdit(self.layoutWidget_12)
        self.label_A_1__B_10.setObjectName(_fromUtf8("label_A_1__B_10"))
        self.horizontalLayout_24.addWidget(self.label_A_1__B_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_24)
        self.label_9 = QLabel(self.layoutWidget_12)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_11.addWidget(self.label_9)
        self.horizontalLayout_25 = QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.keyBind__A_1__B_9 = QLineEdit(self.layoutWidget_12)
        self.keyBind__A_1__B_9.setObjectName(_fromUtf8("keyBind__A_1__B_9"))
        self.horizontalLayout_25.addWidget(self.keyBind__A_1__B_9)
        self.keyBind__A_1__B_10 = QLineEdit(self.layoutWidget_12)
        self.keyBind__A_1__B_10.setObjectName(_fromUtf8("keyBind__A_1__B_10"))
        self.horizontalLayout_25.addWidget(self.keyBind__A_1__B_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_25)
        self.label_10 = QLabel(self.layoutWidget_12)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_11.addWidget(self.label_10)
        self.horizontalLayout_26 = QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.padBind__A_1__B_9 = QLineEdit(self.layoutWidget_12)
        self.padBind__A_1__B_9.setObjectName(_fromUtf8("padBind__A_1__B_9"))
        self.horizontalLayout_26.addWidget(self.padBind__A_1__B_9)
        self.padBind__A_1__B_10 = QLineEdit(self.layoutWidget_12)
        self.padBind__A_1__B_10.setObjectName(_fromUtf8("padBind__A_1__B_10"))
        self.horizontalLayout_26.addWidget(self.padBind__A_1__B_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_20.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_78 = QLabel(self.layoutWidget_12)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.verticalLayout_12.addWidget(self.label_78)
        self.horizontalLayout_27 = QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_A_1__B_11 = QLineEdit(self.layoutWidget_12)
        self.label_A_1__B_11.setObjectName(_fromUtf8("label_A_1__B_11"))
        self.horizontalLayout_27.addWidget(self.label_A_1__B_11)
        self.label_A_1__B_12 = QLineEdit(self.layoutWidget_12)
        self.label_A_1__B_12.setObjectName(_fromUtf8("label_A_1__B_12"))
        self.horizontalLayout_27.addWidget(self.label_A_1__B_12)
        self.verticalLayout_12.addLayout(self.horizontalLayout_27)
        self.label_11 = QLabel(self.layoutWidget_12)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_12.addWidget(self.label_11)
        self.horizontalLayout_28 = QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.keyBind__A_1__B_11 = QLineEdit(self.layoutWidget_12)
        self.keyBind__A_1__B_11.setObjectName(_fromUtf8("keyBind__A_1__B_11"))
        self.horizontalLayout_28.addWidget(self.keyBind__A_1__B_11)
        self.keyBind__A_1__B_12 = QLineEdit(self.layoutWidget_12)
        self.keyBind__A_1__B_12.setObjectName(_fromUtf8("keyBind__A_1__B_12"))
        self.horizontalLayout_28.addWidget(self.keyBind__A_1__B_12)
        self.verticalLayout_12.addLayout(self.horizontalLayout_28)
        self.label_12 = QLabel(self.layoutWidget_12)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_12.addWidget(self.label_12)
        self.horizontalLayout_29 = QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.padBind__A_1__B_11 = QLineEdit(self.layoutWidget_12)
        self.padBind__A_1__B_11.setObjectName(_fromUtf8("padBind__A_1__B_11"))
        self.horizontalLayout_29.addWidget(self.padBind__A_1__B_11)
        self.padBind__A_1__B_12 = QLineEdit(self.layoutWidget_12)
        self.padBind__A_1__B_12.setObjectName(_fromUtf8("padBind__A_1__B_12"))
        self.horizontalLayout_29.addWidget(self.padBind__A_1__B_12)
        self.verticalLayout_12.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_20.addLayout(self.verticalLayout_12)
        self.verticalLayout_9.addLayout(self.horizontalLayout_20)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.pushButton = QPushButton(self.tab_7)
        self.pushButton.setGeometry(QRect(160, 190, 98, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tabWidget_2.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.tabWidget_2.addTab(self.tab_8, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QRect(0, 0, 1163, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSave_Ethogram = QMenu(self.menuFile)
        self.menuSave_Ethogram.setObjectName(_fromUtf8("menuSave_Ethogram"))
        self.menuGamepad = QMenu(self.menubar)
        self.menuGamepad.setObjectName(_fromUtf8("menuGamepad"))
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Movie = QAction(MainWindow)
        self.actionOpen_Movie.setObjectName(_fromUtf8("actionOpen_Movie"))
        self.actionOpen_Image_Sequence = QAction(MainWindow)
        self.actionOpen_Image_Sequence.setObjectName(_fromUtf8("actionOpen_Image_Sequence"))
        self.actionOpen_Norpix_SEQ = QAction(MainWindow)
        self.actionOpen_Norpix_SEQ.setObjectName(_fromUtf8("actionOpen_Norpix_SEQ"))
        self.actionAs_mat_file = QAction(MainWindow)
        self.actionAs_mat_file.setObjectName(_fromUtf8("actionAs_mat_file"))
        self.action_mat = QAction(MainWindow)
        self.action_mat.setObjectName(_fromUtf8("action_mat"))
        self.action_txt = QAction(MainWindow)
        self.action_txt.setObjectName(_fromUtf8("action_txt"))
        self.actionAs_pickle = QAction(MainWindow)
        self.actionAs_pickle.setObjectName(_fromUtf8("actionAs_pickle"))
        self.actionInfo = QAction(MainWindow)
        self.actionInfo.setObjectName(_fromUtf8("actionInfo"))
        self.actionCredits = QAction(MainWindow)
        self.actionCredits.setObjectName(_fromUtf8("actionCredits"))
        self.actionDetect = QAction(MainWindow)
        self.actionDetect.setObjectName(_fromUtf8("actionDetect"))
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionMovie_Tab = QAction(MainWindow)
        self.actionMovie_Tab.setObjectName(_fromUtf8("actionMovie_Tab"))
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionAnalysis = QAction(MainWindow)
        self.actionAnalysis.setObjectName(_fromUtf8("actionAnalysis"))
        self.actionKey_Bindings = QAction(MainWindow)
        self.actionKey_Bindings.setObjectName(_fromUtf8("actionKey_Bindings"))
        self.actionSave_Preferences = QAction(MainWindow)
        self.actionSave_Preferences.setObjectName(_fromUtf8("actionSave_Preferences"))
        self.menuSave_Ethogram.addAction(self.actionAs_mat_file)
        self.menuSave_Ethogram.addAction(self.action_mat)
        self.menuSave_Ethogram.addAction(self.action_txt)
        self.menuSave_Ethogram.addAction(self.actionAs_pickle)
        self.menuFile.addAction(self.actionOpen_Movie)
        self.menuFile.addAction(self.actionOpen_Image_Sequence)
        self.menuFile.addAction(self.actionOpen_Norpix_SEQ)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuSave_Ethogram.menuAction())
        self.menuFile.addAction(self.actionSave_Preferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuGamepad.addAction(self.actionDetect)
        self.menuAbout.addAction(self.actionInfo)
        self.menuAbout.addAction(self.actionCredits)
        self.menuView.addAction(self.actionMovie_Tab)
        self.menuView.addAction(self.actionPreferences)
        self.menuView.addAction(self.actionAnalysis)
        self.menuView.addAction(self.actionKey_Bindings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuGamepad.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(2)
        QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_30.setText(_translate("MainWindow", "animal 1", None))
        self.label_31.setText(_translate("MainWindow", "disjunctive behaviour pair 1", None))
        self.label_A_1__B_1.setText(_translate("MainWindow", "courtship", None))
        self.label_A_1__B_2.setText(_translate("MainWindow", "aggression", None))
        self.label.setText(_translate("MainWindow", "Keyboard", None))
        self.label_2.setText(_translate("MainWindow", "Gamepad", None))
        self.label_32.setText(_translate("MainWindow", "disjunctive behaviour pair 2", None))
        self.label_A_1__B_3.setText(_translate("MainWindow", "wing extension", None))
        self.label_A_1__B_4.setText(_translate("MainWindow", "leg fencing", None))
        self.label_5.setText(_translate("MainWindow", "Keyboard", None))
        self.label_6.setText(_translate("MainWindow", "Gamepad", None))
        self.label_33.setText(_translate("MainWindow", "disjunctive behaviour pair 3", None))
        self.label_A_1__B_5.setText(_translate("MainWindow", "courtship", None))
        self.label_A_1__B_6.setText(_translate("MainWindow", "cleaning", None))
        self.label_7.setText(_translate("MainWindow", "Keyboard", None))
        self.label_8.setText(_translate("MainWindow", "Gamepad", None))
        self.label_38.setText(_translate("MainWindow", "animal 2", None))
        self.label_76.setText(_translate("MainWindow", "disjunctive behaviour pair 1", None))
        self.label_A_1__B_7.setText(_translate("MainWindow", "courtship", None))
        self.label_A_1__B_8.setText(_translate("MainWindow", "aggression", None))
        self.label_3.setText(_translate("MainWindow", "Keyboard", None))
        self.label_4.setText(_translate("MainWindow", "Gamepad", None))
        self.label_77.setText(_translate("MainWindow", "disjunctive behaviour pair 2", None))
        self.label_A_1__B_9.setText(_translate("MainWindow", "wing extension", None))
        self.label_A_1__B_10.setText(_translate("MainWindow", "leg fencing", None))
        self.label_9.setText(_translate("MainWindow", "Keyboard", None))
        self.label_10.setText(_translate("MainWindow", "Gamepad", None))
        self.label_78.setText(_translate("MainWindow", "disjunctive behaviour pair 3", None))
        self.label_A_1__B_11.setText(_translate("MainWindow", "courtship", None))
        self.label_A_1__B_12.setText(_translate("MainWindow", "cleaning", None))
        self.label_11.setText(_translate("MainWindow", "Keyboard", None))
        self.label_12.setText(_translate("MainWindow", "Gamepad", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Preferences", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Keys n Buttons", None))
        self.pushButton.setText(_translate("MainWindow", "GO", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Movie", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Analysis", None))
        self.menuFile.setTitle(_translate("MainWindow", " File I/O", None))
        self.menuSave_Ethogram.setTitle(_translate("MainWindow", "Save Ethogram", None))
        self.menuGamepad.setTitle(_translate("MainWindow", "Gamepad", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.actionOpen_Movie.setText(_translate("MainWindow", "Open Movie", None))
        self.actionOpen_Image_Sequence.setText(_translate("MainWindow", "Open Image Sequence", None))
        self.actionOpen_Norpix_SEQ.setText(_translate("MainWindow", "Open Norpix SEQ", None))
        self.actionAs_mat_file.setText(_translate("MainWindow", "*.xlsx", None))
        self.action_mat.setText(_translate("MainWindow", "*.mat", None))
        self.action_txt.setText(_translate("MainWindow", "*.txt", None))
        self.actionAs_pickle.setText(_translate("MainWindow", "as pickle", None))
        self.actionInfo.setText(_translate("MainWindow", "info", None))
        self.actionCredits.setText(_translate("MainWindow", "credits", None))
        self.actionDetect.setText(_translate("MainWindow", "detect", None))
        self.actionQuit.setText(_translate("MainWindow", "quit", None))
        self.actionQuit.setToolTip(_translate("MainWindow", "quits the program", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionMovie_Tab.setText(_translate("MainWindow", "Movie Tab", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionAnalysis.setText(_translate("MainWindow", "Analysis", None))
        self.actionKey_Bindings.setText(_translate("MainWindow", "Key Bindings", None))
        self.actionSave_Preferences.setText(_translate("MainWindow", "Save Preferences", None))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

